#!/usr/bin/env python

from setuptools import setup
import subprocess
import os
import sys
import shutil

# The directory of this script file.
__here__ = os.path.dirname(os.path.realpath(__file__))

try:
    __version__ = subprocess.check_output(
        'git describe --always --dirty'.split(' ')).decode().splitlines()[0]
    print('VERSION: ' + __version__)
    
    version_file_path = os.path.join(__here__, 'bscan_tools/version.py')

    verson_file_content = (
        "# Autogenerated by the setup.py during build process.\n"
        f"__version__ = '{__version__}'\n")

    with open(version_file_path, 'w') as version_file:
        version_file.write(verson_file_content)
except subprocess.CalledProcessError:
    pass

import bscan_tools.version

__version__ = bscan_tools.version.__version__


setup(
    version=__version__,

    entry_points={
        'console_scripts': [
            'bscan_proc = bscan_tools.bscan_proc:main',
            'generate_tcl = bscan_tools.generate_tcl:main',
        ],
    },
    packages=['bscan_tools'],
    install_requires=['appdirs','bsdl-parser'],
    extras_require={
        'dev': [
            'pylint',
            'pytest',
            'flake8',
            'nanopb'
        ]
    }
)
